new fullpage('#fullpage', {
    anchors:['firstPageAnch', 'secondPageAnch', 'thirdPageAnch', 'fourthPageAnch', 'fifthPageAnch'],
    menu: '#myMenu',
    autoScrolling:true,
    scrollHorizontally: true,
    navigation:false,
    showActiveTooltip:true,
    credits:{enabled: false, label: ' ', position: 'left'},
    animateAnchor: true,
    dragAndMove:true,
    responsiveSlides:true,
    scrollingSpeed:1000,
    fitToSection: true,
    fitToSectionDelay:  1000,
  });
